name: Deployment
on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: krcg.org
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH key
        run: |
          mkdir /home/runner/.ssh
          echo "${{ secrets.KRCG_DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          echo "${{ secrets.KRCG_HOST_ID }}" > /home/runner/.ssh/known_hosts
      - name: Deploy files to server
        run: rsync -rlptq --delete-after -e ssh plugin/ lpanhaleux@krcg.org:projects/lackey.krcg.org/dist
