name: Deployment
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: krcg.org
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KRCG_DEPLOY_KEY }}
      - name: Deploy files to server
        run: rsync -rlptq --delete-after -e ssh plugin/ krcg_deploy@krcg.org:projects/lackey.krcg.org/dist
