name: Deployment
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: krcg.org
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH key
        run: |
          mkdir /home/runner/.ssh
          echo "${{ secrets.KRCG_DEPLOY_KEY }}" > /home/runner/.ssh/krcg_deploy
      - name: Deploy files to server
        run: rsync -rlptq --delete-after -e ssh -l krcg_deploy -i /home/runner/.ssh/krcg_deploy plugin/ krcg.org:projects/lackey.krcg.org/dist
