name: Release
run-name: ${{ github.actor }} is releasing VTES LackeyCCG plugin 🚀
on:
  create:
    ref_type: [tag]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: make update
      - name: Refresh cards list
        run: make cards
      - name: Generate updatelist
        run: make list
      - name: Check for differences
        run: git diff --exit-code
      - name: Generate build folder
        run: make build
      - name: Get tag name
        id: tagname
        uses: olegtarasov/get-tag@v2.1.2
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tagname.outputs.tag }}-vtes-lackey.zip
          path: build/vtes-lackey.zip
      - name: Upload gzip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tagname.outputs.tag }}-vtes-lackey.tar.gz
          path: build/vtes-lackey.tar.gz
