name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: make update
      - name: Check cards list
        run: |
          make cards
          git diff --exit-code
      - name: Check updatelist
        run: |
          make list
          git diff --exit-code
      - name: Generate build folder
        run: make build
